### ISSUE TITLE
How to keep fork up to date

### ISSUE THREAD

**Issue by Gaweph** [Gaweph/MixedRealityToolkit-Unity#4]
## Overview

When trying to keep my fork up to fdate with the upstream repository (Microsoft repository), I am adding commits, which makes my fork ahead of the Microsoft repository.

@StephenHodgson What is the preferred method of keeping my fork up to date with the upstream Microsoft repository? I have been merging the MS repo back into mine, but this is causing me to be commits ahead of Microsoft.

Any advice welcome.

**Comment by StephenHodgson** [comment]
That sounds correct.
